name: Auto Commit and Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Auto Commit and Push
        run: |
          git config --global user.email "mohdhmzkhn1@gmail.com"
          git config --global user.name "hamzak786"
          git add .
          git commit -m "Auto update from GitHub Actions" || echo "No changes to commit"
          git push origin main
